### ISSUE TITLE
 As a mobile user when I select a tag I want to see which leaves on the tree belong to that tag so that I can learn more about and explore the related content of other leaves. 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#100]

**Comment by gissoo** [comment]
@jhimpele @rlskoeser we discussed what the tags look like and how they work on desktop. Please review [what they look like and work on mobile ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=996%3A1955&t=Eh0m0fXGygvTXTfr-1)on Figma as well. – The logic is the same as desktop, the selected tag looks slightly different due to the narrow width on mobile (proposing to make the selected tag full width on mobile)

**Comment by jhimpele** [comment]
Do we still have a plan to reduce the glow area and line width?

**Comment by rlskoeser** [comment]
@gissoo I like the way you've placed the tag directly over the info panel on mobile! The only thing bothering me is that it looks like the X to close the panel and the X to close the tag are close but not quite aligned — could they match?

I think the zoom level on mobile will be slightly different to allow selecting leaves, but I'm assuming that is out of scope here since we haven't decided yet how we're going to handle it.n

My only other question is that I don't think the project info panel shows on mobile after the leaf details are closed. I thought we decide it would be closed after interacting with leaves, and then brought back with the info button (since we need more space for the tree). Or does the intro panel on mobile only close when the user actively closes it? In which case, do we keep track of whether they've closed it or not, and only show it here if they haven't closed it?

**Comment by gissoo** [comment]
> Do we still have a plan to reduce the glow area and line width?

@jhimpele 
- we already revised the line width when you asked for desktop, is it looking too thick on mobile? We can make it thinner on mobile, [how is this looking?](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=996%3A1955&t=Fpe6Sg5esVGcHSxY-1) 
- about the glow area, I can adjust that in the code, it's not efficient to play with that here, I think. I can make it more similar to what you see on desktop.

**Comment by gissoo** [comment]
> @gissoo I like the way you've placed the tag directly over the info panel on mobile! The only thing bothering me is that it looks like the X to close the panel and the X to close the tag are close but not quite aligned — could they match?
> 

- I had to revise the auto-layout structure of the panel to make them match, so now there are more layers in the auto-layout than before, also because I didn't want to widen the x on the tag container. Now the "x" in all mobile panels have a right margin of 12px. I'll need to create a chore to do some clean up on Figma for the change. 

> I think the zoom level on mobile will be slightly different to allow selecting leaves, but I'm assuming that is out of scope here since we haven't decided yet how we're going to handle it.n
> 

- yes, that is out of scope here. 

> My only other question is that I don't think the project info panel shows on mobile after the leaf details are closed. I thought we decide it would be closed after interacting with leaves, and then brought back with the info button (since we need more space for the tree). Or does the intro panel on mobile only close when the user actively closes it? In which case, do we keep track of whether they've closed it or not, and only show it here if they haven't closed it?

- no that was my mistake, [the project intro shouldn't appear at this stage](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1018%3A1294&t=Fpe6Sg5esVGcHSxY-1), thanks for catching. I think it can close without the user having to actively close it.

**Comment by rlskoeser** [comment]
Thanks @gissoo — this looks good to me.

**Comment by jhimpele** [comment]
All looks good to me. Though I'm not sure where you adjust the glow, I do think it could be reduced by up to 50% width/spread.
