### ISSUE TITLE
Replace VizE lab logo in the footer 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#189]

**Comment by gissoo** [comment]
@jhimpele I placed the new logotype in the footer and [here](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1835%3A3698&t=vPBAuQVyxwf8m2JN-1) you can see what it looks like if we don't change the sizes

[here](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1835%3A4071&t=vPBAuQVyxwf8m2JN-1) is how I would suggest the sizes change to fit the logotype in the footer

Note: If you're more likely to keep the current logotype format, i.e. all the PU and VizE lab text beneath the logo then the links above will still be pretty accurate, but if you are thinking of removing some text then the overall height of the logotype will decrease and therefore what you see in the links above will not be accurate. All depends on how you'll revise the logotype.

**Comment by gissoo** [comment]
@jhimpele they are on the same Figma page, they are different but more subtle on desktop than mobile, here:
![Screenshot 2023-05-10 at 1 15 06 PM](https://github.com/Princeton-CDH/lenape-timetree/assets/44615389/b8f2e60a-3caa-4ed7-a0e3-78225dbaf95b)

and here 
![Screenshot 2023-05-10 at 1 15 29 PM](https://github.com/Princeton-CDH/lenape-timetree/assets/44615389/d06e9040-2afd-4035-aaac-479def078396)

– @jhimpele if you'd like to remove the PU line please revise the logotype and make any adjustments necessary and share the revised svg file with me. I agree with removing it, the PU line is also not necessary here since the PU logo almost always can accompany department/center logos.

**Comment by jhimpele** [comment]
Thanks Gissoo! The second mobile is readable, but the desktop is not. I checked again on desktop at 100%....what do you think about the readability of Princeton University on that? Should we design differently? Put the aleph figure to the side, for instance, like NAISIP?

Jeff.

Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
319-320 Burr Hall | Princeton University

vizelab.princeton.edu<http://vizelab.princeton.edu/>


On 5/10/23, 1:18 PM, "gissoo" wrote:


@jhimpele<https://github.com/jhimpele> they are on the same Figma page, they are different but more subtle on desktop than mobile, here:
[Screenshot 2023-05-10 at 1 15 06 PM]<https://user-images.githubusercontent.com/44615389/237466867-b8f2e60a-3caa-4ed7-a0e3-78225dbaf95b.png>

and here
[Screenshot 2023-05-10 at 1 15 29 PM]<https://user-images.githubusercontent.com/44615389/237466958-d06e9040-2afd-4035-aaac-479def078396.png>

– @jhimpele<https://github.com/jhimpele> if you'd like to remove the PU line please revise the logotype and make any adjustments necessary and share the revised svg file with me. I agree with removing it, the PU line is also not necessary here since the PU logo almost always can accompany department/center logos.

**Comment by gissoo** [comment]
@jhimpele putting it to the side might work better, but the readability of PU may remain as is since it's also in a very light weight.

**Comment by jhimpele** [comment]
Ok, I will ask Lula to try another approach and we’ll see what happens.

Thanks,
Jeff.


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
319-320 Burr Hall | Princeton University

vizelab.princeton.edu<http://vizelab.princeton.edu/>


On 5/10/23, 3:22 PM, "gissoo" wrote:


@jhimpele<https://github.com/jhimpele> putting it to the side might work better, but the readability of PU may remain as is since it's also in a very light weight.

**Comment by gissoo** [comment]
@jhimpele @rlskoeser – [I've updated the footer](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1866%3A2750&t=epwVFkcOmF4rJzh8-1) with the newest VizE lab logo Jeff sent me later last week. What do you think? I like this version of the logo much more than the previous ones, thanks to you and Lula, Jeff.

I changed the alignment on mobile so they are right aligned, because visually way more pleasing than the center – aligning them in the center with the new VizE lab logo doesn't work well.

**Comment by jhimpele** [comment]
Well done! The right side alignment looks really good, too.


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
319-320 Burr Hall
vizelab.princeton.edu<http://vizelab.princeton.edu/>


From: gissoo ***@***.***>
Date: Monday, May 15, 2023 at 3:30 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] Replace VizE lab logo in the footer (Issue #189)

@jhimpele<https://github.com/jhimpele> @rlskoeser<https://github.com/rlskoeser> – I've updated the footer<https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?type=design&node-id=1866%3A2750&t=epwVFkcOmF4rJzh8-1> with the newest VizE lab logo Jeff sent me later last week. What do you think? I like this version of the logo much more than the previous ones, thanks to you and Lula, Jeff.

I changed the alignment on mobile so they are right aligned, because visually way more pleasing than the center – aligning them in the center with the new VizE lab logo doesn't work well.

**Comment by rlskoeser** [comment]
The right alignment on mobile is interesting! Almost reverse stair steps. I trust you that it doesn't work centered, I could see how they might fight with each other a bit.

These are fine with me, let's move forward with this update.

**Comment by gissoo** [comment]
Thank you, both! The new VizE lab logo has been uploaded to github. @rlskoeser, the logo's width on mobile is 180px, and height on desktop is 50px. These can be inspected on Figma. I'll go ahead and close this issue.
