### ISSUE TITLE
Design up to five leaves so that they can be used on the time tree

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#27]

**Comment by gissoo** [comment]
@rlskoeser what do you think about [these leaf shapes](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=420%3A2745&t=DJCP8S666b3lau1W-1)? Worth trying them and see how they would look like on your layout?

**Comment by rlskoeser** [comment]
@gissoo these shapes seem fine but I would like to talk a bit to understand how you are imagining they would be implemented.

You don't need to provide them in more than one color or more than one orientation — I need to color them with css, and I can rotate programmatically (although I'll need to think about the logic a bit!).

Were you imagining I would import the svgs and use them directly, sort of like a sprite library? Or do you think it's still feasible to draw these with code based on your designs?

If the latter, I would love to see these leaves lined up in the same orientation so that I can get a better sense of the variation? I can kind of see it, but would like to be more sysematic about it.

**Comment by rlskoeser** [comment]
@gissoo I did some quick svg sketching in d3 to show what I mean, take a look: https://observablehq.com/d/32bcd3234e4021e1

**Comment by gissoo** [comment]
@rlskoeser thank you! here they are oriented in the same direction, please let me know if there is anything else I can do with them in Figma https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=484%3A396&t=CJH26KrwLUoQzVxD-1

**Comment by gissoo** [comment]
@rlskoeser [here is the link](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=548%3A99&t=Rlm4fGep3rXnIfdL-1) to the updated leaves with some specs 

you can inspect each line between the dots on each leaf to see the length of the widest point of each leaf. Let me know if you have any questions

**Comment by gissoo** [comment]
Rebecca has revised the leaves based on my latest revision and new documentation in hand off, and we'll probably refine the leaves at a later point. So I'll go ahead and consider this issue as complete.
