### ISSUE TITLE
Design visual elements that help bring in the Lenape identity on the site

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#28]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele [please take a look at the research I have done on patterns and the patterns I took. ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1188%3A1723&t=XMrNuENzsEaPE8VH-1)I have included the source of all the images. (and have included some interesting resources that may not be relevant at the bottom) 

Here, [see how I have applied the patterns on the mock ups.](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1206%3A2168&t=XMrNuENzsEaPE8VH-1) I have narrowed down to the ones you can see. Please read the notes by each section (The 3 sections represent 3 possibilities, we could go with one of these possibilities, or none, I don't think we can or should combine them) 

Let me know what you think, and there is anything you like. I personally prefer section 3 (applying patterns only to content pages)

**Comment by jhimpele** [comment]
@gissoo Real great work! This adds a lot without overdoing it. Is Keely able to see Sigma? Can we share that page with her on Slack?  I'll get back to you soon with my initial preferences.

**Comment by rlskoeser** [comment]
@gissoo thank you for this. I appreciate you sharing the visuals from your research and the patterns you are drawing on for this.

I like 1.1 with the pattern on the header and footer, although I'm not sure I like the pattern under the roots. 

I like the direction in section 3; my favorites are 3.7 and 3.8, but I do like 3.5 as well.

I think we should limit ourselves to something that will work on both mobile and desktop.  (I presume 1 and 3 do since you did not note otherwise).

The backgrounds with falling leaves are really pretty, but I'm not sure if people be able to recognize the Lenape influence — they might just look like stylized falling leaves to connect with the tree metaphor. I don't know if that matters or not.

I did wonder if there's a way to connect these to the tree visuals a bit more. When I have a chance to get back to revising the  leaf shapes, do you think we could incorporate one of these? The one I thought might work was if we use a simplified version of individual petals within the 5-petalled flower shape you're using for 3.8 (is that a flower or a leaf?); but maybe that's too complicated.

**Comment by jhimpele** [comment]
I had some of the same thoughts….I also wondered about revising leaf shapes!




From: Rebecca Sutton Koeser ***@***.***>
Date: Thursday, March 30, 2023 at 5:22 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Assign ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] Design visual elements that help bring in the Lenape identity on the site (Issue #28)

@gissoo<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgissoo&data=05%7C01%7Cjhimpele%40princeton.edu%7C74892c8651464b484da508db3164dfe9%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638158081544879453%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ux13ljdy%2F1tLHgp6CIF%2Bq%2FoLKwKPI8zj%2BBwkDavYjcU%3D&reserved=0> thank you for this. I appreciate you sharing the visuals from your research and the patterns you are drawing on for this.

I like 1.1 with the pattern on the header and footer, although I'm not sure I like the pattern under the roots.

I like the direction in section 3; my favorites are 3.7 and 3.8, but I do like 3.5 as well.

I think we should limit ourselves to something that will work on both mobile and desktop. (I presume 1 and 3 do since you did not note otherwise).

The backgrounds with falling leaves are really pretty, but I'm not sure if people be able to recognize the Lenape influence — they might just look like stylized falling leaves to connect with the tree metaphor. I don't know if that matters or not.

I did wonder if there's a way to connect these to the tree visuals a bit more. When I have a chance to get back to revising the leaf shapes, do you think we could incorporate one of these? The one I thought might work was if we use a simplified version of individual petals within the 5-petalled flower shape you're using for 3.8 (is that a flower or a leaf?); but maybe that's too complicated.

**Comment by jhimpele** [comment]
Responding here to @rlskoeser 's ideas. Seems like we all like the header and footer in 1. And would also like to see how the footer looks with the pattern excluded from the root area.

Now that I look at 3.5 for content pages, I do like it a lot. But that might clash with the header and footer if it has pattern in 1.  For that reason, or if that will be the case, then I like 3.7 the best.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele Thank you for reviewing and the feedback!! Super helpful! Here are a few responses:
- I think it would be better to use one of these approaches and not combine them (let's pick between 1 and 3, and not do both)
- You're right that in option 2 we can't do it on mobile, that's why I noted "only on desktop". (I don't really like that either)
- We're in a lot of agreements, I also love 3.5, 3.7 and 3.8. 
- I do like the header and footer approach too but I'm finding it hard to see as it's very subtle, maybe it needs a bit of revision so it can be visible without being overpowering. (I have an idea) – I agree that it's better for it to not come under the roots! 
- About incorporating the patterns with the leaf shapes, @rlskoeser I don't know if you have the time to do it! I was trying to simplify this process, if you think it can be done, I'm up for it! It will probably look better :)

**Comment by gissoo** [comment]
We decided to omit the patterns because of some concerns Keely raised about relationships between the Munsee folks with Delaware folks from Oklahoma, and the amount of research or communication it might have needed. Keely further suggested we utilize sycamore leaves. Therefore, we agreed and discussed which of the three approaches I'd proposed the sycamore leaves would be applied to the site. We chose 3.8 (with the leaves appearing only on content pages on the top right edge of the page with various rotation, opacity, and sizes). 

@rlskoeser @jhimpele [please take a look at the sycamore leaves here on desktop and mobile](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1267%3A3848&t=FSaqKRHIk4L15NMU-1) and let me know what you think

**Comment by jhimpele** [comment]
@gissoo I really like this. And your idea of varying their appearance across the pages is great! Nice job

**Comment by rlskoeser** [comment]
This looks great!

**Comment by gissoo** [comment]
thank you! I have uploaded the sycamore leaves as two separate PNGs, one for mobile and another for desktop, to the icon's folder > themes > icons

**Comment by jhimpele** [comment]
Great! Is this a folder in the shared google drive?
