### ISSUE TITLE
Propose a grid / logic for how much space elements take on a page on desktop, tablet, and mobile 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#29]

**Comment by rlskoeser** [comment]
please review what I've implemented and figure out how to adjust — implemented based on our whiteboarding session, but the proposed svg sizes didn't work.

svg is scalable, so we should set the width of the svg to match the full width of the svg container on target desktop width so that our sizes (e.g. 40px leaf widths) will be 40px on the page at that scale; then we can calculate what the zoom level should be for mobile

**Comment by gissoo** [comment]
@rlskoeser what you have right now based on what I see when I inspect in the browser on a 1280 screen is 755.433px for the container that's holding the tree and 248.233px for the panel section. 
Is this correct? 

[You can see what I'm proposing here on Figma  ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=674%3A1809&t=aynnaO3skFFdyoKD-1) – I think it's close, but the main difference is that in my proposal the tree is taking most of the container space, in yours the tree is smaller than it could be. Let me know if there is something I'm missing here.

**Comment by gissoo** [comment]
@rlskoeser based on our conversations today I've revised the grid again, so that on a 1280px screen the svg container is 791px (~62%) and the right margin is 40px, the space between the tree and the panel still remains as 38px. [here are the revised specs on figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=674%3A1809&t=aynnaO3skFFdyoKD-1)

**Comment by rlskoeser** [comment]
Thank you — I'm updating the right side margin, and will make a new task for myself to make the svg display at 1.0 scale on a 1280 screen.
