### ISSUE TITLE
Draw branches so the leaves are more naturally conntected to the tree 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#53]

**Comment by gissoo** [comment]
@jhimpele @rlskoeser Please take a look at this revised version of the branches and let me know what you think, does this look more like a tree to you? (both the branches on the top and the root level) https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=583%3A1466&t=tC6fKoJcyQXJa3QB-1 

– I have included one without leaves and the other three versions with leaves – I prefer the version with filled in leaves in comparison to the ones with no fill color.

**Comment by jhimpele** [comment]
**Really** **great** to see this @gissoo. It does look more like a tree now that the leaves are placed. I also like the filled in leaves rather than just the outlined ones. A few thoughts for tweaking this:

- make the leaves smaller so they appear more proportional to the size of the tree, especially the trunk width. This might allow for more leaves to appear....
- make the trunk a little narrower, for proportion
- extend the bottom of the 4 "branch" line ends deeper down into the trunk, and unevenly if possible. 

What do you think @rlskoeser ?

**Comment by gissoo** [comment]
@jhimpele thanks for the feedback. Because the leaves are tap targets on mobile they have to be at this size/width for web accessibility – We may be able to make them smaller depending on how much space we can dedicate to each leaf's tap target (the requirement is ~48px) – I'll hold off on making the leaves smaller for now till Rebecca and I work on the tree layout in D3 a bit more – More branches and more leaves will definitely fit on the tree. 

I will work on your other two points and will get back to you soon

**Comment by rlskoeser** [comment]
@gissoo thanks for working on this.

I agree with @jhimpele about several things:
- prefer filled in leaves to outlines
- trunk should be narrower
- branches should extend deeper into the trunk 

I understand about the leaf size and tap target constraints; could we make the branch lines thicker so they don't look quite so disproportional?  

I don't understand the logic of how you're drawing the branches — it looks like you have more branches than we do in the data, and they don't match the colors of the leaves. Is this intentional?

**Comment by gissoo** [comment]
@rlskoeser I was focusing on the aesthetics, where is the best place to see and understand the current logic right now? (About how many branches we have).

- I brought up coloring only the leaves in one of the meetings and you both seemed to agree with me, we should have documented it in our decision log :( ... does this seem problematic to you?

**Comment by rlskoeser** [comment]
@gissoo we still have the same five branches we've had from the start (lands + waters, removals, communities, university, resistance + resurgence).  The easiest way to check this is in the google docs (as I just did); the data is in the site, but the branches aren't explicitly visible right now.

I am ok with coloring leaves by branch (agree we should have probably documented). What is confusing to me is that the drawn branches don't match the leaf colors or number of branches.

**Comment by rlskoeser** [comment]
@gissoo I'm creating hidden nodes for the branches to attach the leaves to — currently one for each branch+century, although I'd like to create additional nodes when there are a lot of leaves on one branch in a single century, to allow them to spread out more. Happy to look at with you in person or on zoom if that would help.

Sorry for the confusion in my wording — I didn't mean I expect the branches to be colored; I meant I expect all the leaves on a single branch to be the same color.  Does that match how you are thinking about it?

Please just focus on adjusting the size of the lines and extending them deeper into the trunk — I think I understand enough of the visuals to make a first-draft implementation, which will make the logic of the layout much clearer, and then we can revise.

**Comment by jhimpele** [comment]
Hi Gissoo – I think we are getting closer. I think the trunk can be narrow to seem naturally proportionally to the height of the tree. Also, can we even out the height across the top. As is, it seems like it’s tilting rightward…And I wonder if the light and dark green leaves should be adjacent to each other. Do you think there might be confusion between the discrete categories that way?

I’ll let Rebecca comment on the mapping of the tree onto the data structures….



On 2/1/23, 9:57 AM, "gissoo" wrote:


@rlskoeser<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frlskoeser&data=05%7C01%7Cjhimpele%40princeton.edu%7C6732c4492f8d4f65279908db0464a5ea%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638108602581771675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=M9F8Pz06NRdqgtj1HQUs7NLAX%2BQ2AZS2pdFNcNjKiH8%3D&reserved=0> @jhimpele<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhimpele&data=05%7C01%7Cjhimpele%40princeton.edu%7C6732c4492f8d4f65279908db0464a5ea%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638108602581771675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2qvJGsVmcdZBheXJ7Q4zQloC2edLxJzl1q%2B83%2FF4foI%3D&reserved=0> thank you for all your feedback. I've revised the design here<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsGOn9MZy6ML0yNxuiQJ8u5%2FLenape-Time-Tree%3Fnode-id%3D585%253A2614%26t%3DJj1rf8xOogK7c8Oe-1&data=05%7C01%7Cjhimpele%40princeton.edu%7C6732c4492f8d4f65279908db0464a5ea%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638108602581771675%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ET%2BH7B9puXhR9%2FScdrvrrVv4ykmAZomxrqYVb3Vqkn8%3D&reserved=0> based on your feedback, let me know what you think
·         Rebecca, thank you for clarifying, yes, I agree. The logic was not quite in scope for this issue since I was only considering the visual style of the branches (how far they go into the trunk, and how they are laid out between the two ends) – but based on your comments I have expanded the scope and revised based on your feedback. Is the revised version matching the logic?

**Comment by gissoo** [comment]
@jhimpele thank you for the comment. [Please take a look at the version on the right and let me know what you think](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=607%3A3050&t=h6F568TSyV8CmUcx-1) – I think we can assign colors once we see all the leaves in the implementation, there will be a lot of overlaps.

**Comment by jhimpele** [comment]
Much better trunk and tree shape! I also like the central branches better. Since we’ll have a lot of leaves we might make the right side as tall as the left to allow more leaves on the first default zoom level….Thanks Gissoo.



On 2/1/23, 4:11 PM, "gissoo" wrote:


@jhimpele<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhimpele&data=05%7C01%7Cjhimpele%40princeton.edu%7C17c5019b0dd442a39ac308db0498dc90%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638108826808112752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eg0b8wSF7riohtOa7lVsa22baqaUOofiJjhlLVANBp0%3D&reserved=0> thank you for the comment. Please take a look at the version on the right and let me know what you think<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsGOn9MZy6ML0yNxuiQJ8u5%2FLenape-Time-Tree%3Fnode-id%3D607%253A3050%26t%3Dh6F568TSyV8CmUcx-1&data=05%7C01%7Cjhimpele%40princeton.edu%7C17c5019b0dd442a39ac308db0498dc90%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638108826808268978%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=IVKqkA17WKOpuJb84XKET8YetrLAeCqbQ4Hrpl7f3jk%3D&reserved=0> – I think we can assign colors once we see all the leaves in the implementation, there will be a lot of overlaps.

**Comment by gissoo** [comment]
@jhimpele thank you for writing. I think we'll have to adjust those details in the D3 implementation because they'll depend on where each category will sit on the tree. I totally agree with making more leaves displayed on the default view.
