### ISSUE TITLE
As a user I want to read an introduction to the project before engaging with the tree so that I can navigate it with more understanding and intention.  

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#54]
What's in scope: 
- The visual style of the project intro

**Comment by gissoo** [comment]
@rlskoeser @jhimpele I'd like to know if you're still okay with the visual style of the project intro and how it's displayed like a panel. On desktop it's vertically placed a bit lower in the panel because it's exactly like the other leaf panels but without the "x" button at the top (I've hid the x button), I think not moving the text higher in the panel makes transitioning between content smoother and avoids content from shifting up and down. Let me know what you think, [here is the design on figma ](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=674%3A10896&t=aynnaO3skFFdyoKD-1)

**Comment by rlskoeser** [comment]
@gissoo I think this looks good, but could you put an example of the panel content next to these so I can see the differences you're describing? It's hard for me to get by toggling between this view and the other panel designs.

**Comment by jhimpele** [comment]
I see what you mean.....What if there were a faded (e.g. inactive X there) that become darker and active on the actual panels? The spacing on the landing to the site does look awkward.....

**Comment by gissoo** [comment]
@jhimpele I don't think showing a faded x makes sense because it could imply that it can _sometimes_ be enabled, whereas not showing it means it would never be enabled on the intro panel. 

@rlskoeser @jhimpele I made these two prototypes: (to interact with the first page click on any leaf, then click on the "x" to go back to the previous page) 
1.[ this one is keeping the top marginal space the same for either container ](https://www.figma.com/proto/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?page-id=674%3A10895&node-id=732%3A1113&viewport=790%2C152%2C0.25&scaling=min-zoom&starting-point-node-id=732%3A1113&show-proto-sidebar=1) 
2. [this one is customizing the top marginal space for the intro container. ](https://www.figma.com/proto/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?page-id=674%3A10895&node-id=732%3A1225&viewport=790%2C152%2C0.25&scaling=min-zoom&starting-point-node-id=732%3A1225&show-proto-sidebar=1)

So this was helpful, I don't see any shifting of content that I expected to see – but I just don't think customizing the spacing is necessary here, because the spacing visually works for me – I'm ok if you feel strongly, so let me know.

**Comment by rlskoeser** [comment]
@gissoo I prefer not having to customize the spacing! Glad you think it isn't necessary.

**Comment by jhimpele** [comment]
Agree! Great job @gissoo.


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
vizelab.princeton.edu<http://vizelab.princeton.edu/>


From: Rebecca Sutton Koeser ***@***.***>
Date: Wednesday, February 8, 2023 at 1:30 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] As a user I want to read an introduction to the project before engaging with the tree so that I can navigate it with more understanding and intention. (Issue #54)

@gissoo<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgissoo&data=05%7C01%7Cjhimpele%40princeton.edu%7Ca805244000094970717a08db0a0280a7%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638114778089360727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AY36ZrQq8icQgILlsLJP0fuW%2FqSVLBZiG7Upkc9D8uc%3D&reserved=0> I prefer not having to customize the spacing! Glad you think it isn't necessary.

**Comment by gissoo** [comment]
We've agreed to keep the same top margin within all the panels. I've cleaned up the figma file so it reflects our decision. I'll go ahead and close
