### ISSUE TITLE
As a user when I select a tag I want to see which leaves on the tree belong to that tag so that I can learn more about and explore the related content of other leaves. 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#55]
What's in scope: 
- the logic and sequence of interactions with a tag 
- the visual styles of the selected tag and the leaves in the course of their interaction – UPDATE: explore other visual styles other than the checkmarks to signify clickable tags.

**Comment by gissoo** [comment]
@rlskoeser @jhimpele please read the scope of the issue at the top in the issue description. Please review the interaction logic and the visual styles [here on figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=674%3A6905&t=aynnaO3skFFdyoKD-1) – I've numbered the sequence and included descriptions by each step. 

- Note: I'm proposing that only one tag can be selected at a time, therefore when a tag is selected/active the others are inactive and this is communicated to the user by dimming the checkmarks on the rest of the tags (30% opacity)

**Comment by rlskoeser** [comment]
@gissoo 

- I like the checkbox visual.  
- I agree that only one tag can be selected at a time.

I don't like the idea of having to deselect a tag in order to select a new one — that seems like an unnecessary and non-obvious second click. 

It should be possible to navigate the tree with a tag selected — e.g., to look at other leaves with the same tag. What happens if you close the leaf details? I think we need an indicator of the currently selected tag _outside_ of the panel, and a way to deselect the current tag.

**Comment by rlskoeser** [comment]
@gissoo is the visual of the line with dots something we should be commenting on here?

**Comment by gissoo** [comment]
@rlskoeser yes, please also comment on the visual styles here, it's part of the scope of this issue. 
Thanks for your points, I'll get back to you on them.

**Comment by rlskoeser** [comment]
@gissoo I don't like the black line running through the highlighted leaves; I don't think it's needed or helpful. Are the non-selected leaves intentionally dimmer here?

I would prefer to use the same selection style that we do for the active leaf, if we can. Ah, but maybe we need to differentiate from the currently displayed leaf and all leaves with the selected tag? I would still like to use the same selection/highlight color for both modes, defer to you about if and how they need to be differentiated.

**Comment by jhimpele** [comment]
Agree on both points with @rlskoeser:  cancel the connecting line. And use same selection style used for the active leaf. On second thought: should not the active leaf be distinguished from the related ones that are also highlighted??

**Comment by jhimpele** [comment]
1. I really like the version 1 of the outline + glow plus dim. 
2. I agree with style number 1 on indicating interactivity. Great idea to check with users!
3. I think I like tag exit 1.1. 
4. Not exactly sure what I am looking for with the interaction logic as described. Assuming it is the logic that would imply the style used with tag exit (1.1)

**Comment by rlskoeser** [comment]
Wow, this is a lot! Thanks for the careful notes.

1. I also like version 1 of outline plus glow. I don't particularly like the partial outlines, but I also think they would be difficult to implement.
2. Tag style 1 looks best to me. Thanks for testing interactivity.
3. I like tag exit 1 or 1.1. I prefer 1 because I'm not sure what the line separating tag and X indicates, but I'd be ok with that one.
4. I think I'm tracking with you on the interactivity. I agree that only one tag should be active at a time (we could document it in our decision log if you want).

I do have a few questions about the interaction logic:
  - When a tag is active and leaves without that tag are dimmed, can they still be selected? Or should interaction be disabled when the tag is selected?  My initial instinct was that it feels weird to disable them, but then I thought it would be strange to select one and have the tag active; and thinking about it for a keyboard/screen reader user, it would be pretty nice to be able to tab through only leaves with the corresponding tag! So I'm leaning towards dimmed = not interactive
  - In your interaction scenario 4(a), are you saying that closing the leaf detail also deselects the tag? It doesn't seem necessary/obvious to me that they should both close, but I don't feel strongly about it
  - Should tags be stateful in the URL? i.e., should it be possible to bookmark the timetree with a tag selected? My inclination is yes on this one — which also makes me think it should be possible to share/bookmark tree+tag without having a specific leaf selected, what do you think?

**Comment by gissoo** [comment]
> Wow, this is a lot! Thanks for the careful notes.
> 
>     1. I also like version 1 of outline plus glow. I don't particularly like the partial outlines, but I also think they would be difficult to implement.
> 
>     2. Tag style 1 looks best to me. Thanks for testing interactivity.
> 
>     3. I like tag exit 1 or 1.1. I prefer 1 because I'm not sure what the line separating tag and X indicates, but I'd be ok with that one.
> 

@rlskoeser I also prefer 1.1, it's not logically indicating anything that's different from v1 but it puts more emphasis on the x function, and also tries to look familiar by looking and feeling like an "open tab" to make the double presence of the same chip feel less awkward and more purposeful. 

>     4. I think I'm tracking with you on the interactivity. I agree that only one tag should be active at a time (we could document it in our decision log if you want).
> 

- I'll document it, great idea. 

> 
> I do have a few questions about the interaction logic:
> 
>     * When a tag is active and leaves without that tag are dimmed, can they still be selected? Or should interaction be disabled when the tag is selected?  My initial instinct was that it feels weird to disable them, but then I thought it would be strange to select one and have the tag active; and thinking about it for a keyboard/screen reader user, it would be pretty nice to be able to tab through only leaves with the corresponding tag! So I'm leaning towards dimmed = not interactive
> 

- The interaction with other, non-related leaves should be disabled when a tag is active. From a usability point of view the focus of this scenario should remain on the tagged/related leaves, therefore it doesn't make sense to have all of them still be active, doesn't help the experience to become more focused. I'm glad we're on the same page. 

>     * In your interaction scenario 4(a), are you saying that closing the leaf detail also deselects the tag? It doesn't seem necessary/obvious to me that they should both close, but I don't feel strongly about it
> 

- Yes, I think it's more logical and intuitive that closing the leaf detail would close the tag (because from the experience point of view the "source" of that active tag are the panels that were once open, and it belongs to those panels as it was contained in them. As a user I would expect the tag to close as part of the content of the panel if I'm closing the panel. 

>     * Should tags be stateful in the URL? i.e., should it be possible to bookmark the timetree with a tag selected? My inclination is yes on this one — which also makes me think it should be possible to share/bookmark tree+tag without having a specific leaf selected, what do you think?

- I'm not sure that makes sense on the user's side. I think it makes more sense to be able to bookmark them with relation to a selected leaf.

**Comment by gissoo** [comment]
@jhimpele @rlskoeser I think we are on the same page on most points. 
- I like v1 for leaf styles as well (the one with just the glow for the related tags) 
- I'd also like to move forward with v1 for the tag styles (the one with a light background)
- I like v1.1 better for the tag exit as well 
- I think there are just a few points Rebecca and I should reach an agreement on with the interaction logic and we'll be ready to close this issue.

**Comment by rlskoeser** [comment]
@gissoo I'm willing to follow your lead on these decisions and interaction logic that you think makes most sense. I'm ok with deselecting active tag when panel is closed.

However, I was just thinking about the tags in the url, might have a small wrinkle: what is the expected behavior when you click on a tag in the tag index? Don't we need a way to view the tree with a tag selected without an individual leaf active/open?

**Comment by gissoo** [comment]
> @gissoo I'm willing to follow your lead on these decisions and interaction logic that you think makes most sense. I'm ok with deselecting active tag when panel is closed.
> 
> However, I was just thinking about the tags in the url, might have a small wrinkle: what is the expected behavior when you click on a tag in the tag index? Don't we need a way to view the tree with a tag selected without an individual leaf active/open?
>

_ @rlskoeser for that case it only makes sense to view the tagged leaves without any active leaves / expanded leaf panels. Thanks for bringing that up. 
But it's still not intuitive to view a tag even when "its panel" is closed. How can we bridge the gap in experience with logic here?

**Comment by rlskoeser** [comment]
Documenting what we discussed at standup earlier this week: it seems strange to me to close the tag when you close the leaf, because they are separate to me (although this may be because I know how they are implemented).  A tag doesn't "belong" to a leaf, it's just accessible from a leaf (or from the tag index).  

However, I'm willing to defer to your expertise about what users will expect, and it's not technically difficult — closing the leaf detail panel can also deselect the tag.

I think we've agreed on everything in scope here now, but there may be some cleanup to do in Figma before the selected style and interaction is ready for implementation handoff, so I'll leave this open for now.

**Comment by gissoo** [comment]
Thank you for documenting, @rlskoeser! 
Adding to what you have written: We are making the decision that closing the leaf detail can deselect a tag. Even though it does not align with the implementation logic it is the kind of case where users are not necessarily aware of how the pieces are implemented but rather build an expectation through their experience, what matters here is the intuitiveness of the experience. 

The designs on figma are updated, cleaned up and ready for implementation. I'll deliver the mobile version (for selected tag placement) in a separate issue as this issue has gotten too big.
