### ISSUE TITLE
 As a user when interacting with the site by keyboard I want to know which leaf is selected/active so that I know what I’m looking at 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#83]

**Comment by gissoo** [comment]
@jhimpele @rlskoeser [this is what I propose](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=897%3A7383&t=vGHv3MIzYMOXX912-1) as our focus style on the leaves. Since it's very common for it to be blue I've chosen blue but it needed to be much darker than usual because of problems with accessibility with our dark orange leaf. Let me know if you have thoughts on this

**Comment by jhimpele** [comment]
I'm confused because I thought we were using darker versions of the leaf colors.

**Comment by rlskoeser** [comment]
@gissoo dark blue looks fine to me.

@jhimpele this is for keyboard focus, which is different than the selected leaf.

**Comment by jhimpele** [comment]
Right! Got it.


From: Rebecca Sutton Koeser ***@***.***>
Date: Wednesday, February 22, 2023 at 10:43 AM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] As a user when interacting with the site by keyboard I want to know which leaf is selected/active so that I know what I’m looking at (Issue #83)

@gissoo<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgissoo&data=05%7C01%7Cjhimpele%40princeton.edu%7C9b7a13c1473b4b5740c708db14eb79b5%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638126773834025608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Emw46BiKoQfSWfxsy5j5Rsc%2BHk%2FXxTzpolVGGRjMyqo%3D&reserved=0> dark blue looks fine to me.

@jhimpele<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhimpele&data=05%7C01%7Cjhimpele%40princeton.edu%7C9b7a13c1473b4b5740c708db14eb79b5%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638126773834025608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=t5bY%2FDSwRDUEiWNf7KX5i4c1PH57s6WhQ0evMjs%2FA3o%3D&reserved=0> this is for keyboard focus, which is different than the selected leaf.

**Comment by gissoo** [comment]
@jhimpele a leaf in the focus state is not active/selected yet, but it means it's able to become active (by pressing enter), therefore a focus style needs to be visually different from a select style. 

Thank you, both! I'll go ahead and close the issue. I've added this color to the ["Colors for dev" page on Figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=925%3A7582&t=oEHvSGi3CIU49RI6-1) so the color library is up to date.

**Comment by jhimpele** [comment]
Understood. Thanks @***@***.***>




From: gissoo ***@***.***>
Date: Wednesday, February 22, 2023 at 12:07 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] As a user when interacting with the site by keyboard I want to know which leaf is selected/active so that I know what I’m looking at (Issue #83)

@jhimpele<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhimpele&data=05%7C01%7Cjhimpele%40princeton.edu%7C1bbe5732a4b54beddf3808db14f742cf%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638126824437350722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S4f3e9njRY79Yih9RohZqe8D7gWIA94A5cVhhVJo9Eo%3D&reserved=0> a leaf in the focus state is not active/selected yet, but it means it's able to become active (by pressing enter), therefore a focus style needs to be visually different from a select style.

Thank you, both! I'll go ahead and close the issue. I've added this color to the "Colors for dev" page on Figma<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.figma.com%2Ffile%2FsGOn9MZy6ML0yNxuiQJ8u5%2FLenape-Time-Tree%3Fnode-id%3D925%253A7582%26t%3DoEHvSGi3CIU49RI6-1&data=05%7C01%7Cjhimpele%40princeton.edu%7C1bbe5732a4b54beddf3808db14f742cf%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638126824437350722%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mI9iQ8dGesFOvvxtHj7vO1koPnPN6Kwc7cpe3JU6XQ0%3D&reserved=0> so the color library is up to date.
