### ISSUE TITLE
Propose and document all tag states 

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#90]

**Comment by gissoo** [comment]
@rlskoeser @jhimpele  [here are the tag states on Figma](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=925%3A10602&t=peT75mT4UTb9ILte-1) 

note: I had to make the focus state black here because everything else fails on the brown background. I'm ok to go with black for the leaves' focus state as well (instead of the dark blue).

**Comment by jhimpele** [comment]
Question: what is the significance of hover? I propose switching Hover and Default colors. This way, hover changes the color to the same as if were active, and then clicking (activating) adds the border. What do you think @rlskoeser and @gissoo ?

**Comment by gissoo** [comment]
@jhimpele The hover state is helpful here because there is still a % of users who may not notice the tags to be clickable, so the hover state aids in reaching that awareness. I prefer to not swap hover with default styles, it's a bit too dark to be the default and the light default color will not be good enough for something that is active.

**Comment by jhimpele** [comment]
Thanks @gissoo 
Yes! Now the hover state makes a lot of sense. But if hovering makes a tag darker, that seems counter-intuitive, to me at least. To make it lighter, does that mean making a lot of other changes to colors?

**Comment by rlskoeser** [comment]
These states look good to me.

@jhimpele I think the hover is a slight enough change that it doesn't really matter if it's darker or lighter, what people will notice is the change, which will give the indication that it's clickable.

**Comment by jhimpele** [comment]
@rlskoeser @gissoo that sounds fine. I trust your judgement on what behaviors in this space are typical. Thanks.

**Comment by gissoo** [comment]
thanks both, appreciate your feedback and the questions! Super helpful. @jhimpele @rlskoeser I also agree that it makes more sense for the tags to "light up" on hover (it's common for them to be darker or lighter as Rebecca mentioned, the change is what matters). I was worried that they would be unnoticed, I did a bit of ad-hoc testing and I think it's fine to swap the default and hover colors. I've made the change!  Thank you!

**Comment by gissoo** [comment]
@rlskoeser @jhimpele you didn't tell me – do you prefer that we make the leaves' outlines black for the focus state instead of that deep blue? So the styles match on the site?

**Comment by jhimpele** [comment]
I prefer the blue since it indicates a function of the browser/computer OS rather than tree content or structure. Thanks @gisssoo


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
vizelab.princeton.edu<http://vizelab.princeton.edu/>


From: gissoo ***@***.***>
Date: Monday, March 6, 2023 at 11:46 AM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] Propose and document all tag states (Issue #90)

@rlskoeser<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frlskoeser&data=05%7C01%7Cjhimpele%40princeton.edu%7C763acb7734fe4d8ac71a08db1e6245e1%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638137179696303678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tuitWCdeIqDUr2tDuz7sUjVE3qYTvbm5NP2q32qS55o%3D&reserved=0> @jhimpele<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjhimpele&data=05%7C01%7Cjhimpele%40princeton.edu%7C763acb7734fe4d8ac71a08db1e6245e1%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638137179696303678%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mFNPYabaN6vk0LNmEHxOmuta9g6%2BnomPy8U0GlzgkNA%3D&reserved=0> you didn't tell me – do you prefer that we make the leaves' outlines black for the focus state instead of that deep blue? So the styles match on the site?

**Comment by gissoo** [comment]
Update: we discussed this at our meeting today and agreed on making all focus state black. I have updated the color palette and the leaf states. Thank you!
