### ISSUE TITLE
Design a visual style for the single data point on the trunk of the tree so that users can learn about its distinction from the rest of the leaves

### ISSUE THREAD

**Issue by gissoo** [Princeton-CDH/lenape-timetree#91]

**Comment by gissoo** [comment]
@jhimpele @rlskoeser before I move too far ahead with styles for interaction, and functionality details could you please review [these proposals for the visual style of the trunk data](
https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1028%3A1400&t=4UI5oDQCUitP73J7-1)? 

Note: two of the proposals are plaques and one is a type of small opening of the tree – I don't know what it is exactly called. 

- is there any way we could put a meaningful, short text that would fit on the visual element/plaque in addition to the label?  
- Is this the shortest the label can be?

**Comment by jhimpele** [comment]
@gissoo My favorite style is number two in the darker shade, which would allow a bright font for a short label. What do you think of having it hang from a nail, instead of wrapped around the tree? Some thoughts about the text. What if it only said, "Dedication" and then hovering reveals the text you have plus the content quote?

**Comment by rlskoeser** [comment]
@gissoo I like one or two. I think a plaque is preferable to a the designs that look like a hole or feature of the tree itself.  I agree with Jeff that a nail would be better than a cord around the tree. 

I thought we decided the interaction would be like the leaves — clicking on the visual would open the details in the panel, the same way that leaf details are shown. I don't remember if we discussed labels for this, but I think it should be something short (like just "dedication") if it needs to be labeled at all. I would be nice if the visual was enough without a text label to convey meaning and invite clicking on it, but I'm ok with a text label if that works better.

**Comment by jhimpele** [comment]
Agree with Rebecca here. I’m can’t recall if we specified the interaction, but I agree that “Dedication” is all we need for a label, which could be placed/inscribed on the plaque itself.

Thanks,
Jeff.


Jeffrey Himpele.
Director, VizE Lab for Ethnographic Data Visualization
Lecturer in Anthropology
vizelab.princeton.edu<http://vizelab.princeton.edu/>


From: Rebecca Sutton Koeser ***@***.***>
Date: Friday, March 10, 2023 at 4:55 PM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Assign ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] Design a visual style for the single data point on the trunk of the tree so that users can learn about its distinction from the rest of the leaves (Issue #91)

@gissoo<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fgissoo&data=05%7C01%7Cjhimpele%40princeton.edu%7C3259043e1adb4192460508db21b22de4%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638140821408048120%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L%2FSgvJ5OZRklR2%2FBp19NPiQaRds22jc8JT%2Fe2LJnT%2Fw%3D&reserved=0> I like one or two. I think a plaque is preferable to a the designs that look like a hole or feature of the tree itself. I agree with Jeff that a nail would be better than a cord around the tree.

I thought we decided the interaction would be like the leaves — clicking on the visual would open the details in the panel, the same way that leaf details are shown. I don't remember if we discussed labels for this, but I think it should be something short (like just "dedication") if it needs to be labeled at all. I would be nice if the visual was enough without a text label to convey meaning and invite clicking on it, but I'm ok with a text label if that works better.

**Comment by gissoo** [comment]
@jhimpele @rlskoeser Amazing! YES! a shorter / display label like "Dedication" would be perfect! it's just what I was hoping for. 

[So please review this revised version with a nail](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1040%3A4272&t=kHoIUsn1gDGbkDO8-1) and let me know what you think

I'll open a new issue about the interaction part.

**Comment by jhimpele** [comment]
Better with the nail, @gissoo. How about a short string (upside down V) that hangs the plaque from the nail? Also, it doesn't necessarily have to be straight horizontal, if you want to give it a slight angle.

**Comment by rlskoeser** [comment]
The nail is better but not visible enough; I think it either needs more contrast or separation via a string as Jeff suggested.

**Comment by rlskoeser** [comment]
Commented on the other issue about the string before I saw this one - https://github.com/Princeton-CDH/lenape-timetree/issues/106#issuecomment-1479830438 

How does a nail with a string not make sense? I think it's more common to hang a sign from a string on a nail than to run it around the girth of the tree, esp. since the size of the tree will change as it ages. (-- although a quick google image search is turning up things more like what you've designed!)

**Comment by jhimpele** [comment]
I wondered the same, but then easily found this photo. Though a nail is more common, I now like the less violent relationship with the tree that the string implies.



From: Rebecca Sutton Koeser ***@***.***>
Date: Wednesday, March 22, 2023 at 11:57 AM
To: Princeton-CDH/lenape-timetree ***@***.***>
Cc: Jeffrey D. Himpele ***@***.***>, Mention ***@***.***>
Subject: Re: [Princeton-CDH/lenape-timetree] Design a visual style for the single data point on the trunk of the tree so that users can learn about its distinction from the rest of the leaves (Issue #91)

Commented on the other issue about the string before I saw this one - #106 (comment)<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPrinceton-CDH%2Flenape-timetree%2Fissues%2F106%23issuecomment-1479830438&data=05%7C01%7Cjhimpele%40princeton.edu%7C65abbe665d1d4d1b597c08db2aee2e9a%7C2ff601167431425db5af077d7791bda4%7C0%7C0%7C638150974691656481%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sr%2F7MjCLjLDkM0nN0EYobc%2FZrZ5zjE%2FOs7TmzTNDPDc%3D&reserved=0>

How does a nail with a string not make sense? I think it's more common to hang a sign from a string on a nail than to run it around the girth of the tree, esp. since the size of the tree will change as it ages. (-- although a quick google image search is turning up things more like what you've designed!)

**Comment by gissoo** [comment]
@rlskoeser Right, I mainly saw versions without a nail. Aesthetically I prefer it. Thanks for pointing out the harm of a string, super helpful! Now I don't feel strongly :D ...still not my aesthetic but it doesn't have to be, that's why we have this review process.

**Comment by gissoo** [comment]
@jhimpele @rlskoeser thank you for your feedback on this. Based on your comments here and in #106 I propose that we go with [proposal 2, the version with the string that Jeff preferred](https://www.figma.com/file/sGOn9MZy6ML0yNxuiQJ8u5/Lenape-Time-Tree?node-id=1101%3A4488&t=laysiTUTL0Dz0Ytr-1). I'm archiving the other version with the nail so we can revisit if the implementation is complicated or if you absolutely hate it in a few days.
